env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - "@nuxtjs/eslint-config-typescript"
overrides: []
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module

